import type {
  AnalyticsPeriod,
  AnalyticsKPI,
  MetricDataPoint,
  CategoryAllocation,
  DepartmentCapacity,
  PerformanceInsight,
} from "@/types/analytics";

export const analyticsKPIsByPeriod: Record<AnalyticsPeriod, AnalyticsKPI[]> = {
  "30D": [
    {
      id: "revenue",
      title: "Total Revenue",
      value: "$128,450",
      numericValue: 128450,
      change: "+18.4%",
      trend: "up",
      isGood: true,
      description: "vs previous 30 days",
      highlight: true, // Signature dark-green highlight card
    },
    {
      id: "velocity",
      title: "Sprint Velocity",
      value: "94 pts",
      numericValue: 94,
      change: "+8.2%",
      trend: "up",
      isGood: true,
      description: "24 story pts/wk avg",
    },
    {
      id: "completion",
      title: "Task Completion Rate",
      value: "96.8%",
      numericValue: 96.8,
      change: "+3.1%",
      trend: "up",
      isGood: true,
      description: "112 of 116 deliverables",
    },
    {
      id: "cycle-time",
      title: "Avg. Cycle Time",
      value: "3.2 days",
      numericValue: 3.2,
      change: "-14.5%",
      trend: "down",
      isGood: true, // Decrease in cycle time is positive/good
      description: "from PR to production",
    },
  ],
  "7D": [
    {
      id: "revenue",
      title: "Weekly Revenue",
      value: "$34,200",
      numericValue: 34200,
      change: "+12.1%",
      trend: "up",
      isGood: true,
      description: "vs last week",
      highlight: true,
    },
    {
      id: "velocity",
      title: "Sprint Velocity",
      value: "28 pts",
      numericValue: 28,
      change: "+4.5%",
      trend: "up",
      isGood: true,
      description: "active sprint 14",
    },
    {
      id: "completion",
      title: "Task Completion Rate",
      value: "98.1%",
      numericValue: 98.1,
      change: "+1.8%",
      trend: "up",
      isGood: true,
      description: "26 of 27 tasks",
    },
    {
      id: "cycle-time",
      title: "Avg. Cycle Time",
      value: "2.8 days",
      numericValue: 2.8,
      change: "-8.3%",
      trend: "down",
      isGood: true,
      description: "instant deployments",
    },
  ],
  Quarter: [
    {
      id: "revenue",
      title: "Quarterly Revenue",
      value: "$384,100",
      numericValue: 384100,
      change: "+24.6%",
      trend: "up",
      isGood: true,
      description: "Q3 actuals vs target",
      highlight: true,
    },
    {
      id: "velocity",
      title: "Sprint Velocity",
      value: "295 pts",
      numericValue: 295,
      change: "+16.4%",
      trend: "up",
      isGood: true,
      description: "6 sprints completed",
    },
    {
      id: "completion",
      title: "Task Completion Rate",
      value: "95.4%",
      numericValue: 95.4,
      change: "+4.2%",
      trend: "up",
      isGood: true,
      description: "348 deliverables",
    },
    {
      id: "cycle-time",
      title: "Avg. Cycle Time",
      value: "3.5 days",
      numericValue: 3.5,
      change: "-18.2%",
      trend: "down",
      isGood: true,
      description: "overall sprint velocity",
    },
  ],
  YTD: [
    {
      id: "revenue",
      title: "Annual Revenue (YTD)",
      value: "$1,142,800",
      numericValue: 1142800,
      change: "+31.2%",
      trend: "up",
      isGood: true,
      description: "9 months recorded",
      highlight: true,
    },
    {
      id: "velocity",
      title: "Sprint Velocity",
      value: "860 pts",
      numericValue: 860,
      change: "+22.1%",
      trend: "up",
      isGood: true,
      description: "18 sprints delivered",
    },
    {
      id: "completion",
      title: "Task Completion Rate",
      value: "94.8%",
      numericValue: 94.8,
      change: "+5.0%",
      trend: "up",
      isGood: true,
      description: "982 milestones",
    },
    {
      id: "cycle-time",
      title: "Avg. Cycle Time",
      value: "3.6 days",
      numericValue: 3.6,
      change: "-21.4%",
      trend: "down",
      isGood: true,
      description: "continuous automation",
    },
  ],
};

export const chartDataByPeriod: Record<AnalyticsPeriod, MetricDataPoint[]> = {
  "30D": [
    { period: "Week 1", income: 28400, expenses: 14200, savings: 14200 },
    { period: "Week 2", income: 32600, expenses: 15100, savings: 17500 },
    { period: "Week 3", income: 35100, expenses: 16400, savings: 18700 },
    { period: "Week 4", income: 32350, expenses: 15300, savings: 17050, isProjected: true },
  ],
  "7D": [
    { period: "Mon", income: 4800, expenses: 2100, savings: 2700 },
    { period: "Tue", income: 5600, expenses: 2400, savings: 3200 },
    { period: "Wed", income: 5100, expenses: 2200, savings: 2900 },
    { period: "Thu", income: 6400, expenses: 2600, savings: 3800 },
    { period: "Fri", income: 6100, expenses: 2500, savings: 3600 },
    { period: "Sat", income: 3200, expenses: 1200, savings: 2000 },
    { period: "Sun", income: 3000, expenses: 1100, savings: 1900, isProjected: true },
  ],
  Quarter: [
    { period: "Jul", income: 118000, expenses: 54000, savings: 64000 },
    { period: "Aug", income: 129000, expenses: 58000, savings: 71000 },
    { period: "Sep", income: 137100, expenses: 61000, savings: 76100, isProjected: true },
  ],
  YTD: [
    { period: "Q1", income: 342000, expenses: 162000, savings: 180000 },
    { period: "Q2", income: 384000, expenses: 178000, savings: 206000 },
    { period: "Q3", income: 416800, expenses: 192000, savings: 224800, isProjected: true },
  ],
};

export const categoryAllocations: CategoryAllocation[] = [
  { id: "c1", name: "Engineering & Cloud", amount: 48500, percentage: 38, color: "#3a5030", change: "+12%" },
  { id: "c2", name: "Product & UI/UX", amount: 32000, percentage: 25, color: "#648354", change: "+8%" },
  { id: "c3", name: "Growth & Marketing", amount: 24200, percentage: 19, color: "#4d7c0f", change: "-4%" },
  { id: "c4", name: "Operations & Admin", amount: 14100, percentage: 11, color: "#c2410c", change: "+2%" },
  { id: "c5", name: "Security & Legal", amount: 9650, percentage: 7, color: "#0369a1", change: "-6%" },
];

export const departmentCapacities: DepartmentCapacity[] = [
  { department: "Product Design", utilizedHours: 340, totalCapacity: 400, utilizationRate: 85, activeProjects: 6 },
  { department: "Frontend Team", utilizedHours: 580, totalCapacity: 640, utilizationRate: 91, activeProjects: 9 },
  { department: "Backend & Cloud", utilizedHours: 480, totalCapacity: 600, utilizationRate: 80, activeProjects: 7 },
  { department: "Mobile (iOS/Android)", utilizedHours: 290, totalCapacity: 360, utilizationRate: 81, activeProjects: 4 },
  { department: "QA & Security", utilizedHours: 190, totalCapacity: 280, utilizationRate: 68, activeProjects: 5 },
];

export const performanceInsights: PerformanceInsight[] = [
  {
    id: "ins-1",
    type: "positive",
    title: "Sprint Velocity Up 14%",
    description: "Automated CI/CD pipelines reduced test runtime by 6.4 minutes per PR.",
    metric: "+14.2% pts",
    timestamp: "2 hours ago",
  },
  {
    id: "ins-2",
    type: "positive",
    title: "Cloud Infrastructure Cost Reduced",
    description: "Database composite indexes slashed monthly query computing charges.",
    metric: "-18.5% cost",
    timestamp: "Yesterday",
  },
  {
    id: "ins-3",
    type: "info",
    title: "On-Track Milestone: Mobile Launch",
    description: "Apple Pay & biometric auth deliverables are 75% complete ahead of sprint deadline.",
    metric: "3 days ahead",
    timestamp: "2 days ago",
  },
];
