import type { CalendarEventItem, EventAttendee } from "@/types/calendar";

export const calendarAttendees: EventAttendee[] = [
  { id: "u-1", name: "Shivam Sharma", initials: "SS", avatarColor: "#3a5030" },
  { id: "u-2", name: "Alex Kumar", initials: "AK", avatarColor: "#648354" },
  { id: "u-3", name: "Rahul Mehta", initials: "RM", avatarColor: "#4d7c0f" },
  { id: "u-4", name: "Priya Kapoor", initials: "PK", avatarColor: "#c2410c" },
  { id: "u-5", name: "Elena Rostova", initials: "ER", avatarColor: "#0369a1" },
];

export const initialCalendarEvents: CalendarEventItem[] = [
  {
    id: "evt-1",
    title: "Daily Engineering Standup",
    description: "Brief 15-minute sync on blockers, PR reviews, and sprint velocity.",
    date: "2026-10-01",
    startTime: "10:00 AM",
    endTime: "10:15 AM",
    type: "Team Meeting",
    platform: "Google Meet",
    attendees: [calendarAttendees[0], calendarAttendees[1], calendarAttendees[2]],
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "evt-2",
    title: "Apple Pay Checkout Launch",
    description: "Final QA sign-off and deployment of the biometric checkout components.",
    date: "2026-10-02",
    startTime: "02:00 PM",
    endTime: "03:30 PM",
    type: "Project Deadline",
    platform: "Zoom Video",
    attendees: [calendarAttendees[0], calendarAttendees[1], calendarAttendees[4]],
    color: "bg-orange-50 text-orange-700 border-orange-200",
  },
  {
    id: "evt-3",
    title: "Apartment Rent & Office Lease Due",
    description: "Scheduled recurring corporate office lease payment and utility settlement.",
    date: "2026-10-03",
    startTime: "09:00 AM",
    endTime: "09:30 AM",
    type: "Billing Reminder",
    platform: "Autopay Bank Transfer",
    attendees: [calendarAttendees[0]],
    color: "bg-emerald-50 text-emerald-800 border-emerald-200",
  },
  {
    id: "evt-4",
    title: "Sprint 14 Retrospective & Planning",
    description: "Review sprint deliverables, story points velocity, and assign Sprint 15 backlog items.",
    date: "2026-10-05",
    startTime: "11:00 AM",
    endTime: "12:30 PM",
    type: "Sprint Milestone",
    platform: "Boardroom A / Hybrid",
    attendees: [
      calendarAttendees[0],
      calendarAttendees[1],
      calendarAttendees[2],
      calendarAttendees[3],
    ],
    color: "bg-[var(--color-primary-light)] text-[var(--color-primary-dark)] border-[var(--color-primary)]",
  },
  {
    id: "evt-5",
    title: "Design System & Tokens Review",
    description: "Audit WCAG AA compliance and dark mode semantic token mappings with design team.",
    date: "2026-10-08",
    startTime: "03:00 PM",
    endTime: "04:00 PM",
    type: "Team Meeting",
    platform: "Google Meet",
    attendees: [calendarAttendees[1], calendarAttendees[3]],
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "evt-6",
    title: "Fiber Internet Pro Auto-Debit",
    date: "2026-10-12",
    description: "Monthly fiber internet corporate infrastructure invoice.",
    startTime: "10:00 AM",
    endTime: "10:15 AM",
    type: "Billing Reminder",
    platform: "Stripe Billing",
    attendees: [calendarAttendees[0]],
    color: "bg-emerald-50 text-emerald-800 border-emerald-200",
  },
  {
    id: "evt-7",
    title: "Q4 Roadmap Stakeholder Presentation",
    description: "Executive presentation on mobile user growth and automated accounting rollout.",
    date: "2026-10-15",
    startTime: "01:30 PM",
    endTime: "03:00 PM",
    type: "Sprint Milestone",
    platform: "Main Auditorium",
    attendees: [calendarAttendees[0], calendarAttendees[3]],
    color: "bg-[var(--color-primary-light)] text-[var(--color-primary-dark)] border-[var(--color-primary)]",
  },
  {
    id: "evt-8",
    title: "SOC2 Security & Pen-Test Audit",
    description: "Annual security assessment and third-party penetration testing kick-off.",
    date: "2026-10-20",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    type: "Project Deadline",
    platform: "Zoom Video",
    attendees: [calendarAttendees[0], calendarAttendees[2]],
    color: "bg-orange-50 text-orange-700 border-orange-200",
  },
];
