import type { StatItem, Project, TeamMember, ReminderItem, MonthData, TimeFilter } from "@/types/dashboard";

export const initialStats: StatItem[] = [
  {
    id: "total",
    title: "Total Projects",
    value: 24,
    formattedValue: "24",
    change: "+12.5%",
    description: "vs last month",
    iconName: "FolderKanban",
    positive: true,
  },
  {
    id: "ended",
    title: "Ended Projects",
    value: 12,
    formattedValue: "12",
    change: "+8.2%",
    description: "vs last month",
    iconName: "CircleCheck",
    positive: true,
  },
  {
    id: "running",
    title: "Running Projects",
    value: 8,
    formattedValue: "08",
    change: "+4.5%",
    description: "vs last month",
    iconName: "LoaderCircle",
    positive: true,
    highlight: true,
  },
  {
    id: "pending",
    title: "Pending Projects",
    value: 4,
    formattedValue: "04",
    change: "-2.4%",
    description: "vs last month",
    iconName: "Clock3",
    positive: false,
  },
];

export const initialProjects: Project[] = [
  {
    id: "p1",
    name: "Website Redesign",
    category: "Product Design",
    progress: 72,
    members: ["SS", "AK", "RM", "PK"],
    status: "Running",
    dueDate: "Oct 15, 2026",
  },
  {
    id: "p2",
    name: "Mobile Application",
    category: "Development",
    progress: 48,
    members: ["SS", "RK", "AM"],
    status: "Running",
    dueDate: "Nov 02, 2026",
  },
  {
    id: "p3",
    name: "Marketing Campaign",
    category: "Marketing",
    progress: 100,
    members: ["SS", "AM", "PK", "RK"],
    status: "Completed",
    dueDate: "Sep 20, 2026",
  },
];

export const initialTeamMembers: TeamMember[] = [
  {
    id: "tm1",
    initials: "SS",
    name: "Shivam Sharma",
    role: "Project Lead",
    status: "Online",
    email: "shivam@donezo.io",
  },
  {
    id: "tm2",
    initials: "AK",
    name: "Alex Kumar",
    role: "UI/UX Designer",
    status: "Online",
    email: "alex@donezo.io",
  },
  {
    id: "tm3",
    initials: "RM",
    name: "Rahul Mehta",
    role: "Backend Developer",
    status: "Away",
    email: "rahul@donezo.io",
  },
  {
    id: "tm4",
    initials: "PK",
    name: "Priya Kapoor",
    role: "Product Manager",
    status: "Online",
    email: "priya@donezo.io",
  },
];

export const initialReminder: ReminderItem = {
  id: "rem-1",
  title: "Team Standup Meeting",
  time: "10:00 AM",
  relativeTime: "In 30 min",
  date: "Today · Monday, September 27",
  platform: "Google Meet",
  duration: "30 minutes",
  participants: ["SS", "AK", "RM"],
  additionalCount: 4,
};

export const analyticsDataByFilter: Record<TimeFilter, MonthData[]> = {
  "This Year": [
    { month: "Jan", completed: 45, inProgress: 25, pending: 15 },
    { month: "Feb", completed: 60, inProgress: 32, pending: 20 },
    { month: "Mar", completed: 48, inProgress: 42, pending: 18 },
    { month: "Apr", completed: 72, inProgress: 38, pending: 25 },
    { month: "May", completed: 64, inProgress: 52, pending: 30 },
    { month: "Jun", completed: 82, inProgress: 45, pending: 22 },
    { month: "Jul", completed: 70, inProgress: 60, pending: 28 },
    { month: "Aug", completed: 88, inProgress: 50, pending: 35 },
    { month: "Sep", completed: 76, inProgress: 68, pending: 30 },
    { month: "Oct", completed: 92, inProgress: 55, pending: 24 },
    { month: "Nov", completed: 84, inProgress: 62, pending: 32 },
    { month: "Dec", completed: 96, inProgress: 72, pending: 26 },
  ],
  "This Month": [
    { month: "W1", completed: 65, inProgress: 40, pending: 15 },
    { month: "W2", completed: 80, inProgress: 55, pending: 25 },
    { month: "W3", completed: 72, inProgress: 48, pending: 20 },
    { month: "W4", completed: 94, inProgress: 65, pending: 30 },
  ],
  "Last Year": [
    { month: "Jan", completed: 32, inProgress: 20, pending: 12 },
    { month: "Feb", completed: 45, inProgress: 28, pending: 16 },
    { month: "Mar", completed: 40, inProgress: 35, pending: 14 },
    { month: "Apr", completed: 58, inProgress: 30, pending: 20 },
    { month: "May", completed: 50, inProgress: 44, pending: 24 },
    { month: "Jun", completed: 68, inProgress: 38, pending: 18 },
    { month: "Jul", completed: 58, inProgress: 52, pending: 22 },
    { month: "Aug", completed: 72, inProgress: 42, pending: 28 },
    { month: "Sep", completed: 62, inProgress: 56, pending: 24 },
    { month: "Oct", completed: 75, inProgress: 46, pending: 20 },
    { month: "Nov", completed: 69, inProgress: 50, pending: 26 },
    { month: "Dec", completed: 78, inProgress: 58, pending: 22 },
  ],
};
