import type { TaskItem, TaskAssignee, TaskStatsSummary } from "@/types/task";

export const taskAssignees: TaskAssignee[] = [
  { id: "u-1", name: "Shivam Sharma", initials: "SS", avatarColor: "#3a5030" },
  { id: "u-2", name: "Alex Kumar", initials: "AK", avatarColor: "#648354" },
  { id: "u-3", name: "Rahul Mehta", initials: "RM", avatarColor: "#4d7c0f" },
  { id: "u-4", name: "Priya Kapoor", initials: "PK", avatarColor: "#c2410c" },
  { id: "u-5", name: "Elena Rostova", initials: "ER", avatarColor: "#0369a1" },
];

export const initialTasksList: TaskItem[] = [
  {
    id: "tsk-101",
    title: "Implement Apple Pay & Google Pay checkout flow",
    description: "Build one-click mobile checkout components with biometric authentication fallback.",
    status: "In Progress",
    priority: "Urgent",
    category: "Mobile App",
    dueDate: "Oct 02, 2026",
    dueInDays: 2,
    progress: 75,
    assignees: [taskAssignees[0], taskAssignees[1]],
    subtasks: [
      { id: "st-1", title: "Apple Pay merchant verification", completed: true },
      { id: "st-2", title: "Google Pay client SDK integration", completed: true },
      { id: "st-3", title: "Web checkout fallback UI", completed: true },
      { id: "st-4", title: "Biometric auth testing on iOS", completed: false },
    ],
    attachmentsCount: 4,
    commentsCount: 8,
    tags: ["Mobile", "Checkout", "Payments"],
    createdAt: "2026-09-24",
  },
  {
    id: "tsk-102",
    title: "Audit WCAG AA Contrast Ratios & Dark Mode Tokens",
    description: "Ensure all text/background pairs pass 4.5:1 minimum contrast ratio across both themes.",
    status: "In Review",
    priority: "High",
    category: "Frontend",
    dueDate: "Oct 04, 2026",
    dueInDays: 4,
    progress: 90,
    assignees: [taskAssignees[1], taskAssignees[3]],
    subtasks: [
      { id: "st-5", title: "Color token audit in globals.css", completed: true },
      { id: "st-6", title: "Automated Axe-core testing suite", completed: true },
      { id: "st-7", title: "Manual screen reader navigation pass", completed: false },
    ],
    attachmentsCount: 2,
    commentsCount: 5,
    tags: ["A11y", "Tailwind", "Design System"],
    createdAt: "2026-09-22",
  },
  {
    id: "tsk-103",
    title: "Database Index Optimization for Cash Flow Queries",
    description: "Analyze query execution plans for monthly grouped aggregations and add composite indexes.",
    status: "Completed",
    priority: "High",
    category: "Backend API",
    dueDate: "Sep 28, 2026",
    dueInDays: -2,
    progress: 100,
    assignees: [taskAssignees[2]],
    subtasks: [
      { id: "st-8", title: "Analyze EXPLAIN ANALYZE traces", completed: true },
      { id: "st-9", title: "Create partial indexes on tenant_id + date", completed: true },
      { id: "st-10", title: "Benchmark latency under 10k RPS load", completed: true },
    ],
    attachmentsCount: 1,
    commentsCount: 3,
    tags: ["PostgreSQL", "Performance", "DB"],
    createdAt: "2026-09-20",
  },
  {
    id: "tsk-104",
    title: "Redesign Transaction Details & Split Bill Drawer",
    description: "Craft modern sliding sheet showing receipt image, VAT breakdown, and instant split link.",
    status: "In Progress",
    priority: "Urgent",
    category: "Product Design",
    dueDate: "Oct 01, 2026",
    dueInDays: 1,
    progress: 50,
    assignees: [taskAssignees[0], taskAssignees[3]],
    subtasks: [
      { id: "st-11", title: "Figma high-fidelity prototype", completed: true },
      { id: "st-12", title: "User testing with 5 alpha clients", completed: true },
      { id: "st-13", title: "Component spec handoff to engineering", completed: false },
      { id: "st-14", title: "Framer Motion gesture drag animations", completed: false },
    ],
    attachmentsCount: 7,
    commentsCount: 12,
    tags: ["Figma", "UI/UX", "Drawer"],
    createdAt: "2026-09-25",
  },
  {
    id: "tsk-105",
    title: "Automated Recurring Invoices & Smart Reminder Cron",
    description: "Build scheduled background service to notify clients 3 days before overdue bills.",
    status: "Backlog",
    priority: "High",
    category: "Backend API",
    dueDate: "Oct 08, 2026",
    dueInDays: 8,
    progress: 0,
    assignees: [taskAssignees[2], taskAssignees[4]],
    subtasks: [
      { id: "st-15", title: "Cron scheduler configuration", completed: false },
      { id: "st-16", title: "Email & SMS notification webhook", completed: false },
      { id: "st-17", title: "Idempotency keys for invoice generation", completed: false },
    ],
    attachmentsCount: 3,
    commentsCount: 2,
    tags: ["Cron", "Billing", "Reminders"],
    createdAt: "2026-09-27",
  },
  {
    id: "tsk-106",
    title: "Interactive Semicircle Gauge for Financial Health",
    description: "Build animated SVG arc gauge component supporting responsive scaling and tooltip markers.",
    status: "Completed",
    priority: "Medium",
    category: "Frontend",
    dueDate: "Sep 29, 2026",
    dueInDays: -1,
    progress: 100,
    assignees: [taskAssignees[0], taskAssignees[1]],
    subtasks: [
      { id: "st-18", title: "SVG arc trigonometry helpers", completed: true },
      { id: "st-19", title: "Framer motion path length animation", completed: true },
      { id: "st-20", title: "Hatched pattern slice for remaining", completed: true },
    ],
    attachmentsCount: 2,
    commentsCount: 4,
    tags: ["SVG", "Charts", "Framer Motion"],
    createdAt: "2026-09-21",
  },
  {
    id: "tsk-107",
    title: "Customer Onboarding Walkthrough & Product Tours",
    description: "Design interactive spotlight tour highlighting workspace switcher, quick actions, and search.",
    status: "Backlog",
    priority: "Low",
    category: "Product Design",
    dueDate: "Oct 14, 2026",
    dueInDays: 14,
    progress: 0,
    assignees: [taskAssignees[3]],
    subtasks: [
      { id: "st-21", title: "Define 4-step onboarding script", completed: false },
      { id: "st-22", title: "Spotlight backdrop mask component", completed: false },
    ],
    attachmentsCount: 1,
    commentsCount: 1,
    tags: ["Growth", "Onboarding"],
    createdAt: "2026-09-28",
  },
  {
    id: "tsk-108",
    title: "Export Monthly Accounting Summaries to CSV & PDF",
    description: "Provide one-click export with category breakdown, tax receipts, and formatted timestamps.",
    status: "In Review",
    priority: "Medium",
    category: "Frontend",
    dueDate: "Oct 05, 2026",
    dueInDays: 5,
    progress: 85,
    assignees: [taskAssignees[1], taskAssignees[2]],
    subtasks: [
      { id: "st-23", title: "CSV streaming serializer", completed: true },
      { id: "st-24", title: "Print stylesheet for clean PDF export", completed: true },
      { id: "st-25", title: "Unit tests for date formatters", completed: false },
    ],
    attachmentsCount: 3,
    commentsCount: 6,
    tags: ["Export", "CSV", "Reporting"],
    createdAt: "2026-09-23",
  },
];

export const initialTaskStats: TaskStatsSummary = {
  total: 28,
  inProgress: 8,
  inReview: 4,
  completed: 16,
  completionRate: 94,
};
