import type { TeamMemberItem, TeamStatsSummary } from "@/types/team";

export const initialTeamList: TeamMemberItem[] = [
  {
    id: "tm-1",
    name: "Shivam Sharma",
    initials: "SS",
    avatarColor: "#3a5030",
    role: "Lead Architect & Fullstack",
    department: "Frontend Engineering",
    accessLevel: "Admin",
    status: "Online",
    email: "shivam@shivam.io",
    location: "San Francisco, USA",
    timezone: "PST (UTC-7)",
    activeTasksCount: 4,
    completedTasksCount: 38,
    skills: ["Next.js", "React 19", "Tailwind", "Architecture"],
    joinedDate: "Jan 2024",
  },
  {
    id: "tm-2",
    name: "Alex Kumar",
    initials: "AK",
    avatarColor: "#648354",
    role: "Senior Frontend Engineer",
    department: "Frontend Engineering",
    accessLevel: "Member",
    status: "Online",
    email: "alex@shivam.io",
    location: "London, UK",
    timezone: "BST (UTC+1)",
    activeTasksCount: 3,
    completedTasksCount: 26,
    skills: ["TypeScript", "Framer Motion", "Design Systems", "A11y"],
    joinedDate: "Mar 2024",
  },
  {
    id: "tm-3",
    name: "Rahul Mehta",
    initials: "RM",
    avatarColor: "#4d7c0f",
    role: "Staff Backend Engineer",
    department: "Backend & Infra",
    accessLevel: "Member",
    status: "Away",
    email: "rahul@shivam.io",
    location: "Berlin, Germany",
    timezone: "CEST (UTC+2)",
    activeTasksCount: 5,
    completedTasksCount: 31,
    skills: ["PostgreSQL", "Go", "Distributed Systems", "Redis"],
    joinedDate: "Feb 2024",
  },
  {
    id: "tm-4",
    name: "Priya Kapoor",
    initials: "PK",
    avatarColor: "#c2410c",
    role: "Principal Product Designer",
    department: "Product & Design",
    accessLevel: "Member",
    status: "Online",
    email: "priya@shivam.io",
    location: "New York, USA",
    timezone: "EST (UTC-4)",
    activeTasksCount: 2,
    completedTasksCount: 42,
    skills: ["Figma", "Design Systems", "Prototyping", "User Research"],
    joinedDate: "Nov 2023",
  },
  {
    id: "tm-5",
    name: "Elena Rostova",
    initials: "ER",
    avatarColor: "#0369a1",
    role: "Senior Mobile Engineer",
    department: "Mobile Engineering",
    accessLevel: "Member",
    status: "Online",
    email: "elena@shivam.io",
    location: "Austin, USA",
    timezone: "CST (UTC-5)",
    activeTasksCount: 3,
    completedTasksCount: 19,
    skills: ["Swift", "Kotlin", "React Native", "Apple Pay"],
    joinedDate: "Apr 2024",
  },
  {
    id: "tm-6",
    name: "David Chen",
    initials: "DC",
    avatarColor: "#263620",
    role: "Cloud & SecOps Lead",
    department: "Backend & Infra",
    accessLevel: "Member",
    status: "Offline",
    email: "david@shivam.io",
    location: "Singapore",
    timezone: "SGT (UTC+8)",
    activeTasksCount: 2,
    completedTasksCount: 24,
    skills: ["AWS", "Kubernetes", "SOC2 Compliance", "Terraform"],
    joinedDate: "May 2024",
  },
  {
    id: "tm-7",
    name: "Sarah Jenkins",
    initials: "SJ",
    avatarColor: "#b45309",
    role: "Lead QA Automation Engineer",
    department: "QA & Security",
    accessLevel: "Member",
    status: "Online",
    email: "sarah@shivam.io",
    location: "Toronto, Canada",
    timezone: "EST (UTC-4)",
    activeTasksCount: 3,
    completedTasksCount: 33,
    skills: ["Playwright", "Jest", "Load Testing", "CI/CD"],
    joinedDate: "Jun 2024",
  },
  {
    id: "tm-8",
    name: "Marcus Vance",
    initials: "MV",
    avatarColor: "#b91c1c",
    role: "Senior Product Manager",
    department: "Product & Design",
    accessLevel: "Admin",
    status: "Away",
    email: "marcus@shivam.io",
    location: "Seattle, USA",
    timezone: "PST (UTC-7)",
    activeTasksCount: 4,
    completedTasksCount: 45,
    skills: ["Roadmapping", "Sprint Planning", "Data Analytics", "Scrum"],
    joinedDate: "Jan 2024",
  },
];

export const initialTeamStats: TeamStatsSummary = {
  total: 24,
  online: 18,
  departmentsCount: 5,
  capacityUtilization: 91,
};
